### ISSUE TITLE
compatibility with superfancy clouds?

### ISSUE THREAD

**Issue by slovinsqui** [Soulphur0/ElytraAeronautics#7] opened 2023-02-24 02:09 UTC
I found this mod that I would like to use in combo with elytra aeronautics, It would give players flying above cloud layers some cool visuals, but it does not work because of the cloud rendering

https://www.curseforge.com/minecraft/mc-mods/superfancyclouds-refabricated

I am FAR from being a coder so I don´t know if asking for something clearly impossible

**Comment by Soulphur0** [comment] 2023-02-26 13:51
I have to find some time to try that mod out and see what is the problem. if the problem is that clouds don't show up, I'm in the middle of next update, where compatiblity with other mods that use custom cloud rendering should be mitigated, I will proably even add some button to toogle off EAN clouds so other mod's clouds are the ones beign used.

If you refer to have multiple 3D cloud layers here's an answer:

It is probably not impossible to adapt this mod to EAN, it's very likely it uses a similar premise to how cloud layers work with my mod. The thing is, I would probably need to spend a lot of time to adapt my mod to this mod, likely doubling the amount of code it already has or more. Having to write the mod again to put it in some way, since EAN is very small, it wouldn't be impossible technically speaking, but very time consuming and I lack time. 

Since this mod itsn't popular enough yet I don't want to spend that much time on an adaptation for it, other than being able to disable EAN clouds and use this mod's clouds, which is easier to do and I will work to make them compatible, that's for sure.

As a side note, the things is, I already had plans to add 3D clouds for my mod, in a different way this mod does it to be fair, I am not sure when I will be able to do this as I lack time, and I am currently paused in the middle of next update that will bring a lot of improvements to the mod in general, some extra customization for cloud layers and bug fixes; but due to a lot of things I've been busy with IRL, I don't know when I will have this update ready, hopefully I'll be able to finish and release it at the end of next month, but I can't promise much.

If you want to inform me about anyting else, feel free to do so, regards!

**Comment by slovinsqui** [comment] 2023-03-04 19:07
sure thing! as I said, i don´t know a thing about modding but I am aware of how difficult it gets, so take all the time you need to get things done (breaks are also important)
Best of luck for ya c:

**Comment by Soulphur0** [comment] 2023-08-21 04:18
This issue was fixed in the latest version, you can know use Elytra Aeronautics and set the 'useEanCloudRendering' setting to 'false' in order to use SuperFancyClouds' cloud rendering system, while keeping flight features.

**Closed by Soulphur0** 2023-08-21 04:18 UTC
