### ISSUE TITLE
Game crashes when I land on the ground, and flying is very broken.

### ISSUE THREAD

**Issue by Slooshie1** [Soulphur0/ElytraAeronautics#3] opened 2022-01-10 00:46 UTC
My game crashes with this mod enabled when I try to land on the ground while flying with an elytra. Also, I set both the curve value and the exponential value to -64 so that all layers of the minecraft world will affect the speed of flying, but sometimes, and quite often, the player will stop moving forward entirely and when the game recognizes that I have stopped moving it will take me out of flight mode and I will plummet to the ground.

**Comment by Soulphur0** [comment] 2022-01-10 03:10
I'm sorry for that, I'm currently working on a major fix on flight, it will be out as soon as I can finish it. I will also look into making the speed curve more clear to set up and less buggy in that same patch. 
For now, try to set the beginning of the curve at something like - 100 and the exponential at - 64.
Minecraft, specially since the last update, takes more resources when chunk loading, unfortunately if a lot of world is generated for the first time, so if you fly very far away very fast it will take some time for the game to catch up.
I haven't come with any crashes when trying to land buy I will reproduce your setup and look into that, disabling the gamerule "doElytraCheck" _might_ help with sudden stops, it's worth trying it. 

This week I come back to school so I might not be able to work on the mod for a few days, for now try what I suggested and if you come with any other problem, please, tell me, reporting any kind of issue helps in the mod's development. 

Thank you very much for reporting this issue and sorry for the inconvenience.

**Comment by Slooshie1** [comment] 2022-01-11 04:49
I don't know what happened, but it fixed itself. I think it was just a one-time issue after I broke the game when I set the multiplier way too high and flew faster than light lmao. Thank you for your response and the advice, though, I might use it to fine-tune my flight speed, as I am still trying to make it not too fast and not too slow.

**Comment by Soulphur0** [comment] 2022-01-12 02:28
> I don't know what happened, but it fixed itself. I think it was just a one-time issue after I broke the game when I set the multiplier way too high and flew faster than light lmao. Thank you for your response and the advice, though, I might use it to fine-tune my flight speed, as I am still trying to make it not too fast and not too slow.

I'm glad to hear that, still I will make sure I go over some potential bugs with flight. I also will try to make the speed multiplier more clear, it is a constant the game uses in the code as it is, and rising it up just a bit, like 0.0001 makes a notable difference. 

It is best to add a very low decimal value and test it out. Also, the setting's tooltip tells you an speed estimate based on the value you set, give it a look.

I will definetly take that confusing constant out and try to make a "introduce max speed in km/h or mph" at some point.

I will close this issue, feel free to open a new one if you encounter any other problem!

**Closed by Soulphur0** 2022-01-12 02:28 UTC
Labels: bug
